# 책 323page 에서는 travis-ci.org 로 진행하였으나 이 프로젝트는 travis.com으로 진행
language: java
jdk:
  - openjdk8
branches:
  only:
    - master

#Travis CI 서버의 Home
cache:
  directories:
    -  '$HOME/.me/repository'
    -  '$HOME/.gradle'
script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - sungwoony@kakao.com

before_deploy:
  - zip -r web_service *
  - mkdir -p deploy
  - mv web_service.zip deploy/web_service.zip

# S3로 파일업로드 혹은 CodeDeploy로 배포 등 외부서비스와 연동될 행위들을 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: freelec-springboot-build-minguinho # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-untill-deployed: true


